"""empty message

Revision ID: a6e4cf255eec
Revises: 
Create Date: 2021-11-24 20:59:51.395037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e4cf255eec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('carisyou_url', sa.Text(), nullable=True),
    sa.Column('aws_url', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=30), nullable=False),
    sa.Column('imported_domestic', sa.String(length=30), nullable=False),
    sa.Column('price', sa.String(length=40), nullable=False),
    sa.Column('fuel_efficiency', sa.String(length=30), nullable=True),
    sa.Column('fuel', sa.String(length=30), nullable=True),
    sa.Column('car_grade', sa.String(length=30), nullable=True),
    sa.Column('appearance', sa.String(length=30), nullable=True),
    sa.Column('grade_name', sa.String(length=50), nullable=True),
    sa.Column('on_sale', sa.String(length=30), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('discontinued_date', sa.Date(), nullable=True),
    sa.Column('ride_capacity', sa.String(length=30), nullable=True),
    sa.Column('top_speed', sa.String(length=30), nullable=True),
    sa.Column('displacement', sa.String(length=30), nullable=True),
    sa.Column('engine_type', sa.String(length=30), nullable=True),
    sa.Column('drive_method', sa.String(length=30), nullable=True),
    sa.Column('fuel_efficiency_rating', sa.String(length=30), nullable=True),
    sa.Column('price_int', sa.String(length=40), nullable=True),
    sa.Column('price_int_low', sa.BigInteger(), nullable=True),
    sa.Column('price_int_high', sa.BigInteger(), nullable=True),
    sa.Column('displacement_int', sa.BigInteger(), nullable=True),
    sa.Column('fuel_efficiency_int', sa.String(length=30), nullable=True),
    sa.Column('fuel_efficiency_int_low', sa.Float(), nullable=True),
    sa.Column('fuel_efficiency_int_high', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mbti_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mbti_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('worldcup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worldcup')
    op.drop_table('mbti_result')
    op.drop_table('mbti_question')
    op.drop_table('car')
    # ### end Alembic commands ###
